### ISSUE TITLE
Possible to add brackets { } after 'className=' ?

### ISSUE THREAD

**Issue by mdodge-ecgrow** [zackls/ReactCssAutocomplete#1]
Hello, thank you for a very helpful plugin!  I appreciate to ability to have className in my intellisense now.  Just wondering if in the autocomplete function, you could have the option to do this: `<div className={}>` and automatically put the cursor between the brackets.

**Comment by zackls** [comment]
@mdodge-ecgrow Glad you find the plugin useful!

I'm not sure I understand your request, do you mean that after typing the last character of `className=`, you'd like to automatically have brackets appear, with your cursor in the center of them? `className={}`

I don't think this behavior makes sense for users who want to directly type strings, ie: `className="..."`

**Comment by mdodge-ecgrow** [comment]
Yes, that is what I was asking.  That makes sense though about the strings.  Was hoping it could be added as an option to turn on or off.  Nonetheless, having `className` in the intellisense is a huge help.
Thanks!
